spring:
  application:
    name: silver_lady_s

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/silver_lady_s_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update} # prod uchun validate/none tavsiya
    show-sql: ${SHOW_SQL:true}
    open-in-view: false

server:
  port: ${PORT:8080}

app:
  jwt:
    issuer: ${JWT_ISSUER:silver_lady_s}
    secret: ${JWT_SECRET:CHANGE_ME_SUPER_LONG_RANDOM_SECRET}  # prod: env orqali berilsin
    access-token-minutes: ${JWT_ACCESS_MIN:120}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

  bootstrap:
    admin:
      enabled: ${BOOTSTRAP_ADMIN_ENABLED:false}
      email: admin@silverladys.uz
      password: Admin123!
#  bootstrap:
#    admin:
#      enabled: ${BOOTSTRAP_ADMIN_ENABLED:true}
#      email: ${BOOTSTRAP_ADMIN_EMAIL:admin@silverladys.uz}
#      password: ${BOOTSTRAP_ADMIN_PASSWORD:Admin123!}
#      full-name: ${BOOTSTRAP_ADMIN_FULLNAME:Admin}
