name: Deploy to Production

on:
  push:
    branches: [ prod ]

permissions:
  contents: read

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build JAR
        run: mvn -DskipTests package --no-transfer-progress

      - name: Copy JAR to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: target/*.jar,Dockerfile,.dockerignore
          target: /root/silver_lady_s_backend/
          strip_components: 0

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          command_timeout: 20m
          script: |
            set -e
            docker pull eclipse-temurin:17-jre-jammy
            cd /root/silver_lady_s_backend
            docker compose -f docker-compose.prod.yaml up -d --build --no-deps app
            docker image prune -f
            echo "Deploy muvaffaqiyatli yakunlandi"
